---
variables:  # global variables applying to all jobs unless explicitly overwritten
    REQUESTS_CA_BUNDLE: /etc/ssl/certs/ca-certificates.crt  # this tells python to actually use the installed system certificates
    DENO_STD_VERSION: 0.134.0  # Deno std version to use in Deno binding code

.default run rules:
    rules:  # determine if job should run or not; evaluation stops at the first matching rule!
        - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'  # in general, do run on a MR
        - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS'  # do not run for a branch if there is also a MR for that branch - this prevents running two pipelines for the same commit
          when: never
        - if: '$CI_PIPELINE_SOURCE == "schedule"'  # do not run on schedule, we want to do this explicitly on the job
          when: never
        - if: '$CI_COMMIT_BRANCH == "main"'  # if we get here the trigger was not a MR, in that case we only want to run for commits on branch main right now
        - if: '$CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+(?:-\w+)*$/'  # also run for version tags

workflow:
    rules:
        - if: '$CI_PIPELINE_SOURCE == "schedule"'  # run on schedule
        - !reference [.default run rules, rules]

default:  # default settings applying to all jobs unless explicitly overwritten
    image: rust:latest
    tags:
        - egfx  # this tag will be used to automatically select the Gitlab runner configured for our group

stages:  # stages are executed in the order they are defined; if no direct dependencies between jobs are defined, all jobs of a stage need to finish successfully before the next stage begins
    - Build Rust
    - Test Rust
    - Lint Rust
    - Lint
    - Audit Rust
    - Generate Deno bindings
    - Publish

.setup rust:
    before_script:
        - rustc --version
        - cargo --version

.setup wasm-pack:
    before_script:
        - curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
        - wasm-pack --version

.setup nodejs:
    before_script:
        - apt update
        - apt install -y nodejs
        - node --version

Build Rust Code:
    stage: Build Rust
    before_script:
        - !reference [.setup rust, before_script]
        - !reference [.setup wasm-pack, before_script]
    script:
        - wasm-pack build --release
        - 'WASM_BINDGEN=`[[ -z "${XDG_CACHE_HOME}" ]] && find $HOME/.cache -name wasm-bindgen || find $HOME/.cache $XDG_CACHE_HOME -name wasm-bindgen`'
        - '[[ -z "${WASM_BINDGEN}" ]] && echo wasm-bindgen not found && (exit 1)'
        - 'cp $WASM_BINDGEN .'
    rules:
        - !reference [.default run rules, rules]
    artifacts:
        paths:
            - "target/wasm32-unknown-unknown/release/wasm_minisign_verify.wasm"
            - "wasm-bindgen"
        expire_in: 2 hours

Generate Deno bindings:
    stage: Generate Deno bindings
    variables:
        GIT_STRATEGY: none
    script:
        - './wasm-bindgen --target deno --typescript --out-dir pkg target/wasm32-unknown-unknown/release/wasm_minisign_verify.wasm'
    rules:
        - !reference [.default run rules, rules]
    needs:
        - "Build Rust Code"
    dependencies:
        - "Build Rust Code"
    artifacts:
        paths:
            - "pkg"
        expire_in: 2 hours

Bundle WASM for Deno:  # this job fixes some problems in the glue code currently generated by wasm-bindgen which prevents us from caching the WASM for offline distribution
    stage: Generate Deno bindings
    variables:
        GIT_DEPTH: 1
    before_script:
        - command -v base64 &> /dev/null  # check if base64 is available
        - command -v sed &> /dev/null  # check if sed is available
        - command -v cat &> /dev/null  # check if cat is available
    script:
        - base64 --wrap=0 pkg/wasm_minisign_verify_bg.wasm | sed -e 's/\//\\\//g' > pkg/wasm_minisign_verify.base64  # base64-encode our WASM and escape all / so we can pass this to sed
        - echo "s/wasmCode = await (await fetch(wasm_url)).arrayBuffer();/wasmCode = base64.decode(\"`cat pkg/wasm_minisign_verify.base64`\")/" > command.sed
        - sed -i -f command.sed "pkg/wasm_minisign_verify.js"  # if WASM is supposed to be loaded via http: or https: load inline base64 instead
        - rm pkg/wasm_minisign_verify.base64  # remove base64 encoded payload again so we do not package it
        - rm command.sed  # remove sed command again so we do not package it
        - echo -e "import * as base64 from \"https://deno.land/std@$DENO_STD_VERSION/encoding/base64.ts\";\n`cat pkg/wasm_minisign_verify.js`" > pkg/wasm_minisign_verify.js  # prepend import of base64 from Deno std to the file
    rules:
        - !reference [.default run rules, rules]
    needs:
        - "Generate Deno bindings"
    dependencies:
        - "Generate Deno bindings"
    artifacts:
        paths:
            - "pkg"
        expire_in: 2 hours

Test Rust Code:
    stage: Test Rust
    before_script:
        - !reference [.setup rust, before_script]
        - !reference [.setup wasm-pack, before_script]
        - !reference [.setup nodejs, before_script]
    script:
        - cargo test --verbose
        - wasm-pack test --node
    needs: ["Build Rust Code"]
    rules:
        - !reference [.default run rules, rules]

Lint Rust Code with Clippy:
    stage: Lint Rust
    before_script:
        - !reference [.setup rust, before_script]
    script:
        - rustup component add clippy
        - cargo clippy -- -D warnings
    needs: ["Build Rust Code"]
    rules:
        - !reference [.default run rules, rules]

Check Rust code formatting:
    stage: Lint Rust
    before_script:
        - !reference [.setup rust, before_script]
    script:
        - rustup component add rustfmt
        - cargo fmt -- --check
    needs: ["Build Rust Code"]
    rules:
        - !reference [.default run rules, rules]

Audit Rust dependencies:
    stage: Audit Rust
    before_script:
        - !reference [.setup rust, before_script]
    script:
        - cargo install cargo-audit
        - cargo audit
    needs: []
    rules:  # determine if job should run or not; evaluation stops at the first matching rule!
        - if: '$CI_PIPELINE_SOURCE == "schedule"'  # run on schedule
        - !reference [.default run rules, rules]

Lint CI:
    image: artifacts.core.pke.fhm.de/peo-docker-public-local/python:3
    stage: Lint
    before_script:
        - pip install yamllint
    script:
        - "yamllint .gitlab-ci.yml"
    needs: []
    rules:
        - if: '$CI_PIPELINE_SOURCE == "merge_request_event" || $CI_PIPELINE_SOURCE == "push"'
          changes:  # run if any of the following changes on a MR or push
              - '.gitlab-ci.yml'
        - if: '$CI_PIPELINE_SOURCE != "merge_request_event" && $CI_PIPELINE_SOURCE != "push" && $CI_PIPELINE_SOURCE != "schedule"'
          when: on_success  # always run for other pipeline sources

Publish version to Artifactory (exact version):
    stage: Publish
    image: $ARTIFACTORY_FQDN/peo-docker-public-local/alpine:3.15  # alpine image with P7S1 SSL certificates preinstalled
    variables:
        GIT_DEPTH: 1
    before_script:
        - command -v md5sum &> /dev/null  # check if md5sum is available
        - command -v sha1sum &> /dev/null  # check if sha1sum is available
        - command -v sha256sum &> /dev/null  # check if sha256sum is available
        - command -v awk &> /dev/null  # check if awk is available
        - apk add --no-cache curl
        - command -v curl &> /dev/null  # check if curl is available
        - curl -fL https://install-cli.jfrog.io | sh  # install Jfrog CLI
        - jf config import $ARTIFACTORY_CONFIG_BASE64  # load prepared configuration
        - jf rt ping  # test if we can connect
        - apk add --no-cache git
    script:
        - cd pkg/
        - jf rt upload --flat=false --quiet --recursive "*" egfx-generic-public-local/deno_modules/wasm-minisign-verify@`git tag --points-at HEAD`/
    dependencies:
        - "Bundle WASM for Deno"
    rules:
        - if: '$CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+(?:-\w+)*$/'  # also run for version tags

Publish version to Artifactory (latest):
    stage: Publish
    image: $ARTIFACTORY_FQDN/peo-docker-public-local/alpine:3.15  # alpine image with P7S1 SSL certificates preinstalled
    variables:
        GIT_STRATEGY: none  # do not clone repo, we only want to talk to Artifactory anyway
    before_script:
        - command -v md5sum &> /dev/null  # check if md5sum is available
        - command -v sha1sum &> /dev/null  # check if sha1sum is available
        - command -v sha256sum &> /dev/null  # check if sha256sum is available
        - command -v awk &> /dev/null  # check if awk is available
        - apk add --no-cache curl
        - command -v curl &> /dev/null  # check if curl is available
        - curl -fL https://install-cli.jfrog.io | sh  # install Jfrog CLI
        - jf config import $ARTIFACTORY_CONFIG_BASE64  # load prepared configuration
        - jf rt ping  # test if we can connect
    script:
        - cd pkg/
        - jf rt upload --flat=false --quiet --recursive --sync-deletes=egfx-generic-public-local/wasm-minisign-verify/ "*" egfx-generic-public-local/deno_modules/wasm-minisign-verify/
    dependencies:
        - "Bundle WASM for Deno"
    rules:
        - if: '$CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+$/'  # also run for version tags
